
version: '3'
services:
  app:
    container_name: pg_api_quick2
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - db
  db:
    container_name: db2
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_USER: ${user}
      POSTGRES_DB: ${db_name}